item {
  id: 1
  name: 'Cethosia cydippe'
}

item {
  id: 2
  name: 'Danaid eggfly'
}

item {
  id: 3
  name: 'Alucitidae'
}

item {
  id: 4
  name: 'Agape chloropyga'
}

item {
  id: 5
  name: 'Swamp tiger'
}

item {
  id: 6
  name: 'Argyreus hyperbius'
}

item {
  id: 7
  name: 'birdwing'
}

item {
  id: 8
  name: 'black-spotted white'
}

item {
  id: 9
  name: 'Bogong'
}

item {
  id: 10
  name: 'Emperor Gum'
}

item {
  id: 11
  name: 'Euploea alcathoe'
}

item {
  id: 12
  name: 'Euploea tulliolus'
}

item {
  id: 13
  name: 'Giant Wood'
}

item {
  id: 14
  name: 'Golden Sun'
}

item {
  id: 15
  name: 'Grapevine'
}

item {
  id: 16
  name: 'graphiumEurypylus'
}

item {
  id: 17
  name: 'graphiumMacfarlanei'
}

item {
  id: 18
  name: 'graphiummacleayanus'
}

item {
  id: 19
  name: 'Leafwing'
}

item {
  id: 20
  name: 'Lichen'
}

item {
  id: 21
  name: 'Monarch butterfly'
}

item {
  id: 22
  name: 'purple beak'
}

item {
  id: 23
  name: 'redBandedJezebel'
}

item {
  id: 24
  name: 'Samia Cynthia'
}

item {
  id: 25
  name: 'Thallarcha albicollis'
}

item {
  id: 26
  name: 'Uraniidae'
}

item {
  id: 27
  name: 'vindulaArsinoe'
}

item {
  id: 28
  name: 'Eschemon rafflesia'
}

item {
  id: 29
  name: 'whiteBandedPlane'
}




